import { ThemeConfig } from '@/config/theme.config'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Home from './page'
import React from 'react'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <React.StrictMode>
        <ThemeConfig>
          <Home />
        </ThemeConfig>
      </React.StrictMode>
    </html>
  )
}
