import { ThemeConfig } from "@/config/theme.config";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import React from "react";
import { NavBar } from "@/common/NavBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <React.StrictMode>
        <ThemeConfig>
          <body>
            <NavBar />
            {children}
          </body>
        </ThemeConfig>
      </React.StrictMode>
    </html>
  );
}
